# -----------------------------------
# IIS-SecureProxy jwilder 版本 
# 2025-10-01
# 和 jwilder/nginx-proxy 搭配使用
# -----------------------------------

services:
  smartm-proxy:
    image: nginx:latest
    container_name: smartm-proxy
    restart: always
    expose:
      - "80"                            # 只在 docker network 內部開放
    networks:
      - nginx-proxy
    environment:
      - TZ=Asia/Taipei
      # 兩個對外網域都交給 jwilder 入口
      - VIRTUAL_HOST=www.smartm.com
      - LETSENCRYPT_HOST=www.smartm.com
      - LETSENCRYPT_EMAIL=justin@blockcode.com.tw
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled:/etc/nginx/conf.d:ro
      - ./redirects.map.conf:/etc/nginx/redirects.map.conf:ro  # 由 Excel 轉出
      - ./acme:/var/www/acme:ro              # ★ 新增這行

networks:
  nginx-proxy:
    external: true
